### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by Tommy8634** [kong78/collectibles-on-radar-gta-sa#1]
First would like to start by saying amazing work, now I am new to SDK and as expected had some issues setting everything up(totally on me of course) but once I did the mod worked amazingly, However there was one issue, at one point in the code you call for .DrawRadarOrMap my VS was saying this was wrong and after looking online found out it was .m_bDrawRadarOrMap. now I'm new to SDK so i'm not sure if it was something i was doing but just in case something has changed I just thought I would let you know. once again amazing what you done I looked for so long for a mod like this and could only find yours that suited what I wanted.

**Comment by kong78** [comment]
Yep, plugin-sdk got updated. 43a4b46924f2a7ace429ae2df1d50827da7685c5 fixed it.
