### ISSUE TITLE
Default On/Off option

### ISSUE THREAD

**Issue by MoneyAllDay** [kong78/collectibles-on-radar-gta-sa#4]
Is there any chance that you could add an option so we can set the mod default to on or off?

Currently the mod is always on when starting the game, it would be nice using this mod more as a helping tool instead of seeing the blips at all times on the hud/map.

I know there is a toggle shortcut(F12) but it gets repetitive having to press it every time i start the game.

**Comment by kong78** [comment]
You may set the virtual key code of the on/off key in the INI file.
`123` for the `F12` key for instance.
